void* gbm_bo_create() { return 0; }
void* gbm_bo_create_with_modifiers() { return 0; }
void* gbm_bo_destroy() { return 0; }
void* gbm_bo_get_device() { return 0; }
void* gbm_bo_get_handle() { return 0; }
void* gbm_bo_get_handle_for_plane() { return 0; }
void* gbm_bo_get_height() { return 0; }
void* gbm_bo_get_modifier() { return 0; }
void* gbm_bo_get_offset() { return 0; }
void* gbm_bo_get_plane_count() { return 0; }
void* gbm_bo_get_stride_for_plane() { return 0; }
void* gbm_bo_get_width() { return 0; }
void* gbm_bo_import() { return 0; }
void* gbm_bo_map() { return 0; }
void* gbm_bo_unmap() { return 0; }
void* gbm_create_device() { return 0; }
void* gbm_device_destroy() { return 0; }
void* gbm_device_get_fd() { return 0; }
void* gbm_device_is_format_supported() { return 0; }
